swagger: '2.0'
info:
  title: Example API
  description: Example API to demonstrate the SwaggerAPI module for revel
  version: 1.0.0
host: localhost:9000
basePath: /api
tags:
  - name: Item
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /endpoint:
    get:
      x-revel-controller-action: App.Endpoint
      description: |
        Prints a simple message
      responses:
        '200':
          description: A simple response
          schema:
            $ref: '#/definitions/Message'
  /items:
    get:
      x-revel-controller-action: Items.List
      tags:
        - Item
      description: List of all items sorted by id
      responses:
        '200':
          schema:
            type: array
            items:
              $ref: '#/definitions/Item'
    post:
      x-revel-controller-action: Items.Create
      tags:
        - Item
      description: Creates a new item with name `name`
      parameters:
        - in: body
          name: Item
          description: Item object to create
          schema:
            $ref: '#/definitions/Item'
      responses:
        '200':
          schema:
            $ref: '#/definitions/Item'
  /items/{id}:
    get:
      x-revel-controller-action: Items.Read
      tags:
        - Item
      description: Read a new item with {id}
      parameters:
        - in: path
          name: id
          description: the item's id
          type: integer
      responses:
        '200':
          schema:
            $ref: '#/definitions/Item'
        '404':
          schema:
            $ref: '#/definitions/RevelError'
    put:
      x-revel-controller-action: Items.Update
      tags:
        - Item
      description: Updates a new item with {id}
      parameters:
        - in: path
          name: id
          description: the item's id
          type: integer
        - in: query
          name: name
          description: the item's new name
          type: string
      responses:
        '200':
          schema:
            $ref: '#/definitions/Item'
        '404':
          schema:
            $ref: '#/definitions/RevelError'
    delete:
      x-revel-controller-action: Items.Delete
      tags:
        - Item
      description: Deletes a new item with {id}
      parameters:
        - in: path
          name: id
          description: the item's id
          type: integer
      responses:
        '200':
          schema:
            $ref: '#/definitions/Item'
        '404':
          schema:
            $ref: '#/definitions/RevelError'
definitions:
  Message:
    type: object
    properties:
      message:
        type: string
  Item:
    type: object
    properties:
      id:
        type: integer
        minimum: 0
      name:
        type: string
  RevelError:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
